config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
  	namespace :v1 do
  		 resources :students
  	end
  end
  get 'home/courses',to:'home#courses'
  get 'home/single_course',to: 'home#single_course'
  get 'home/about_us',to:'home#about_us'
  get 'home/blog',to:'home#blog'
  get 'home/contact_us',to:'home#contact_us'
  get 'students/index',to: 'students#index'
  get 'students/finance',to: 'students#finance'
  get 'students/exam', to: 'students#exam'
  get 'home/index',to: 'home#index'
  root 'home#index' 
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :finances
	belongs_to :department
end

app/controllers/api/v1/students_controller.rb
module Api
	module V1
		class StudentsController < ApplicationController
			respond_to :json
			def index
				@student = allStd
				render json: {status: 'SUCCESS',message:'STUDENTS LOADED',data:@student},status: :ok
			end

			def show
				@student = singleStd
				render json: {status: 'SUCCESS',message: 'STUDENT LOADED',data:@student},status: :ok
			end

			def create
				@student = Student.new(student_params)

				if @student.save
					render json: {status: 'SUCCESS',message: 'STUDENT LOADED',data:@student},status: :ok
					else
					render json: {status: 'Error',message: 'the file could not be created',data:@student.errors},status: :unprocessable_entity
				end
			end

			def update
				@student = Student.find(params[:id])

				if @student.update_attributes(student_params)
					render json: {status: 'SUCCESS',message: 'STUDENT EDITED',data:@student},status: :ok
				else
					render json: {status: 'Error',message: 'the file could not be edited',data:@student.errors},status: :unprocessable_entity
				end
			end

			def destroy
				@student = Student.find(params[:id])
				
				if @student.destroy
					render json: {status: 'Deleted item', message: 'item Deleted'},status: :ok
				else
					render json: {status: 'ERROR', message: 'item not Deleted', data:@student.errors},status: :unprocessable_entity
				end
			end

			private

			def student_params
				  params.permit(:firstName, :lastName, :department_id)
			end

			def allStd
				@allStd = Student.find_by_sql("SELECT id,firstName,lastName FROM students")
				return @allStd
			end

			def singleStd
				@singleStd = Student.find(params[:id])
				@toReturn = @singleStd.firstName+" "+@singleStd.lastName
				return @toReturn
			end
		end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy] 
  # POST /students
  # POST /students.json
  def index
    @student = Student.all
  end

  def show
    @student = Student.all
  end

  def finance
    
  end

  def exam
    
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstName, :lastName,:department_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_navigation.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default navbar-top" role="navigation">
			  <div class="navbar-header">
                    <h2 class="nav-barbrand">Student portal</h2>
               </div>
			</nav>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row">
			 <div class="col-md-3">
               	<div class="navbar-default sidebar" role="navigation">
               	    <div class="sidebar-nav navbar-collapse">
               	        <ul class="nav" id="side-menu">
               	            <li>
               	                <%= link_to ' Profile',students_index_path %></i>
               	            </li>
               	            <li>
               	            	<%= link_to '   Finance',students_finance_path %>
               	            </li>
               	            <li>
               	                <%= link_to 'Exams',students_exam_path %></i>
               	            </li>
               	        </ul>
               	    </div>
               	</div>
             </div>
             <div class="col-md-9">

app/views/students/exam.html.erb
<%= render 'navigation' %>
             	<div class="panel panel-primary">
             	                            <div class="panel-heading">
             	                               Student Exam
             	                            </div>
             	                            <div class="panel-body">
             	                            	<div class="panel panel-default">
             	                            	                            <div class="panel-heading">
             	                            	                                Hover Rows
             	                            	                            </div>
             	                            	                            <!-- /.panel-heading -->
             	                            	                            <div class="panel-body">
             	                            	                                <div class="table-responsive">
             	                            	                                    <table class="table table-hover">
             	                            	                                        <thead>
             	                            	                                            <tr>
             	                            	                                                <th>#</th>
             	                            	                                                <th>Unit</th>
             	                            	                                                <th>Grade</th>
             	                            	                                            </tr>
             	                            	                                        </thead>
             	                            	                                        <tbody>
             	                            	                                            <tr>
             	                            	                                                <td>1</td>
             	                            	                                                <td>Phyc 110</td>
             	                            	                                                <td>A</td>
             	                            	                                            </tr>
             	                            	                                            <tr>
             	                            	                                                <td>2</td>
             	                            	                                                <td>Math 220</td>
             	                            	                                                <td>B</td>
             	                            	                                            </tr>
             	                            	                                            <tr>
             	                            	                                                <td>3</td>
             	                            	                                                <td>Comp 210</td>
             	                            	                                                <td>A</td>
             	                            	                                            </tr>
             	                            	                                        </tbody>
             	                            	                                    </table>
             	                            	                                </div>
             	                            	                                <!-- /.table-responsive -->
             	                            	                            </div>
             	                            	                            <!-- /.panel-body -->
             	                            	                        </div>
             	                            </div>
             	                            <div class="panel-footer text-center">
             	                               Iris University
             	                            </div>
             	                        </div>
             </div>
	</div>
</div>

app/views/students/finance.html.erb
<%= render 'navigation' %>
             	<div class="panel panel-primary">
             	                            <div class="panel-heading">
             	                               Student Finance
             	                            </div>
             	                            <div class="panel-body">
             	                    <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                
                                                <td>Total fee</td>
                                                <td>50,000/=</td>
                                            </tr>
                                            <tr>
                                                
                                                <td>Paid</td>
                                                <td>24,000/=</td>
                                            </tr>
                                            <tr>
                                                
                                                <td>Balance</td>
                                                <td>26,000/=</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
             	                            </div>
             	                            <div class="panel-footer text-center">
             	                               Iris University
             	                            </div>
             	                        </div>
             </div>
	</div>
</div>

app/views/students/index.html.erb
<%= render 'navigation' %>
             	<div class="panel panel-primary">
             	                            <div class="panel-heading">
             	                               Student Profile
             	                            </div>
             	                            <div class="panel-body">
             	                            		                    <div class="table-responsive">
             	                            	                       <table class="table">
             	                            	                           <tbody>
             	                            	                               <tr>
             	                            	                                   
             	                            	                                   <td>Name:</td>
             	                            	                                   <td>Tatiana Manois</td>
             	                            	                               </tr>
             	                            	                               <tr>
             	                            	                                   
             	                            	                                   <td>Course: </td>
             	                            	                                   <td>Education</td>
             	                            	                               </tr>
             	                            	                               <tr>
             	                            	                                   
             	                            	                                   <td>Year of study: </td>
             	                            	                                   <td>Y2S2</td>
             	                            	                               </tr>
             	                            	                                 <tr>
             	                            	                                   
             	                            	                                   <td>phone: </td>
             	                            	                                   <td>+254 712 345 678</td>
             	                            	                               </tr>
             	                            	                           </tbody> 
             	                            	                       </table>
             	                            	                   </div>
             	                            </div>
             	                            <div class="panel-footer text-center">
             	                               Iris University
             	                            </div>
             	                        </div>
             </div>
	</div>
</div>