config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, :defaults => {:format => :json} do
  	namespace :v1 do
  		 resources :students
  	end
  end
  get 'home/courses',to:'home#courses'
  get 'home/single_course',to: 'home#single_course'
  get 'home/about_us',to:'home#about_us'
  get 'home/blog',to:'home#blog'
  get 'home/contact_us',to:'home#contact_us'
  get 'students/index',to: 'students#index'
  get 'students/finance',to: 'students#finance'
  get 'students/exam', to: 'students#exam'
  get 'home/index',to: 'home#index'
  root 'home#index' 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
  def about_us
  	
  end

  def contact_us
  	
  end

  def blog
  	
  end 

  def courses
  	
  end
  
  def single_course
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<!-- Footer -->
    <footer class="footer">        
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="widget widget-text">
                       <%= image_tag('logo-f1.png') %>
                    </div>
                </div><!-- /.col-md-12 -->    
            </div><!-- /.row -->    

            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="sidebar-inner-footer">
                        <div class="widget widget-infomation">
                            <ul class="flat-information">
                                <li class="email"><a href="mailto:AlitStudios@gmail.com">AlitStudios@gmail.com</a></li>  
                                <li class="phone"><a href="61383766284">+61 3 8376 6284</a></li>
                                <li class="address">121 King Street, Melbourne  Victoria 3000 Australia</li>
                                
                            </ul>
                        </div>
                    </div><!-- /.sidebar-inner-footer -->    
                </div><!-- /.col-md-12 -->    
            </div><!-- /.row -->    

            <div class="row"> 
                <div class="footer-widgets">
                    <div class="col-md-2">  
                        <div class="widget widget_categories">
                            <h4 class="widget-title">Links</h4>
                            <ul>
                                <li><a href="#">ourses</a></li>
                                <li><a href="#">Events</a></li>
                                <li><a href="#">FAQs</a></li>
                                <li><a href="#">Maintenance</a></li>
                            </ul>
                        </div><!-- /.widget -->      
                    </div><!-- /.col-md-2 --> 

                    <div class="col-md-2">  
                        <div class="widget widget_categories">
                            <h4 class="widget-title">SUPPORT</h4>
                            <ul>
                                <li><a href="#">Documentation</a></li>
                                <li><a href="#">Forums</a></li>
                                <li><a href="#">Language Packs</a></li>
                                <li><a href="#">Release Status</a></li>
                            </ul>
                        </div><!-- /.widget -->      
                    </div><!-- /.col-md-2 --> 

                    <div class="col-md-2">  
                        <div class="widget widget_categories">
                            <h4 class="widget-title">Our School</h4>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                                <li><a href="#">Become a Teacher</a></li>
                                <li><a href="#">Our Teacher</a></li>
                            </ul>
                        </div><!-- /.widget -->      
                    </div><!-- /.col-md-2 --> 

                    <div class="col-md-6">
                        <div class="widget widget_mc4wp">
                            <div id="mc4wp-form-1" class="form mc4wp-form clearfix">
                                <form method="post">
                                    <p> <label>Subscribe now and receive weekly newsletter with educational materials, new courses, interesting posts, popular books and much more!</label></p>
                                    <p>
                                    <input type="email" name="EMAIL" placeholder="Your email address" required="">                                   
                                    <input type="submit" value="SUBSCRIBE">
                                    </p>
                               </form>
                            </div>
                        </div><!-- /.widget_mc4wp -->
                    </div><!-- /.col-md-6 -->
                </div><!-- /.footer-widgets -->
            </div><!-- /.row -->    
        </div><!-- /.container -->
    </footer>

    <!-- Bottom -->
    <div class="bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="line-top"></div>
                </div>
            </div>
            <div class="row">
                <div class="container-bottom">
                    <div class="col-md-6">
                        <div class="copyright"> 
                            <p>© Copyright <a href="#">Alitstudio</a> 2015. All Rights Reserved.
                            </p>
                        </div>                   
                    </div><!-- /.col-md-6 -->

                    <div class="col-md-6">
                        <ul class="flat-socials text-right">
                            <li class="facebook">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li class="twitter">
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li class="instagram">
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li class="linkedin">
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>              
                    </div><!-- /.col-md-6 -->
                </div><!-- /.container-bottom -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>

    <!-- Go Top -->
    <a class="go-top">
        <i class="fa fa-angle-up"></i>
    </a> 

app/views/home/_navigation.html.erb
<!-- Header -->            
    <header id="header" class="header clearfix"> 
        <div class="header-wrap clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                        <div id="logo" class="logo">
                            <%= link_to root_path do %>
                            <%= image_tag('logo.png') %>
                            <% end %>
                        </div><!-- /.logo -->
                        <div class="btn-menu">
                            <span></span>
                        </div><!-- //mobile menu button -->
                    </div><!-- /.col-md-2 -->
                    <div class="col-md-10">
                        <div class="nav-wrap">
                            
                            <nav id="mainnav" class="mainnav">
                                <ul class="menu">
                                    <li><%= link_to 'Courses',home_courses_path %></li>  
                                    <li><a href="#">Pages</a>
                                        <ul class="submenu right-sub-menu"> 
                                            <li><%= link_to 'About us',home_about_us_path %></li>
                                            
                                            <li><%= link_to 'Contact Us',home_contact_us_path %></li>
                                        </ul><!-- /.submenu -->
                                    </li>
                                    <li><%= link_to 'Blog',home_blog_path %></li>
                                </ul><!-- /.menu -->
                            </nav><!-- /.mainnav -->  
                        </div><!-- /.nav-wrap -->
                    </div><!-- /.col-md-10 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
            <div class="show-search">
                <a href="#"><i class="fa fa-search"></i></a>                
            </div><!-- /.show-search -->
            <div class="nav-search">
                <div class="container"> 
                    <div class="col-md-12">
                       <div class="top-search" id="s1">
                            <aside id="search-4" class="widget widget_search">
                                <form role="search" method="get" class="search-form">
                                    <label>
                                        <input type="search" class="search-field" placeholder="Search …" value="" name="s" title="Search for:">
                                    </label>
                                    <input type="submit" class="search-submit" value="Search">
                                </form>
                            </aside>                    
                        </div><!-- /.top-search -->
                    </div>
                </div>
            </div><!-- /.nav-search -->             
        </div><!-- /.header-inner --> 
    </header><!-- /.header -->

app/views/home/_shelf.html.erb
<div class="top">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="language">        
                        <ul class="flat-information">
                            <li class="email"><a href="mailto:garielcruz300@gmail.com">garielcruz300@gmail.com</a></li>
                            <li class="phone"><a href="+254740154227">+254 740 154 227</a></li>
                            <li class="current"><a href="#">English</a>
                                <ul>  
                                    <li class="en"><a href="#">English</a></li>
                                    <li class="ge"><a href="#">Kiswahili</a></li> 
                                </ul>
                            </li>
                        </ul>
                    </div><!-- /.language -->
                </div><!-- /.col-md-6 -->   
                <div class="col-md-6">
                    <div class="top-navigator">
                        <ul>
                            <li><%= link_to 'Student Log in', students_index_path %></li>
                            <li><%= link_to 'Staff Log in', new_admin_user_session_path %></li>
                            
                        </ul>
                    </div><!-- /.top-navigator --> 
                </div><!-- /.col-md-6 -->              
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.top -->

app/views/home/contact_us.html.erb
 <!-- Boxed -->
     <div class="boxed">

     <%= render 'shelf' %>
     <%= render 'navigation' %>
 <!-- Page title -->
    <div class="page-title parallax parallax1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">                    
                    <div class="page-title-heading">
                        <h1 class="title">Contact Us</h1>
                        <div class="breadcrumbs">
                            <ul>
                                <li><%= link_to 'Home',root_path %></li>
                                <li>All Course 2</li>
                            </ul>                   
                        </div>
                    </div><!-- /.page-title-captions --> 
                    
                </div><!-- /.col-md-12 -->  
            </div><!-- /.row -->  
        </div><!-- /.container -->                      
    </div><!-- /.page-title -->

    <!-- Flat contact -->
    <section class="flat-row pad-bottom0px">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="wrap-contactform-home1">
                        <form id="contactform" class="flat-contact-form border-radius field-large text-large" method="post" action="./contact/contact-process.php">
                            <div class="field clearfix">      
                                <div class="wrap-type-input">                    
                                    <div class="input-wrap name">
                                        <input type="text" value="" tabindex="1" placeholder="Your name" name="name" id="name" required>
                                    </div>
                                    <div class="input-wrap email">
                                        <input type="email" value="" tabindex="2" placeholder="Your email" name="email" id="email" required>
                                    </div>
                                    <div class="input-wrap last Subject">
                                        <input type="text" value="" placeholder="Subject" name="subject" id="subject" >
                                    </div>  
                                </div>
                                <div class="textarea-wrap">
                                    <textarea class="type-input" tabindex="3" placeholder="Your Message" name="message" id="message-contact" required></textarea>
                                </div>
                            </div>
                            <div class="submit-wrap">
                                <button>send</button>
                            </div>
                        </form><!-- /.comment-form -->   
                    </div><!-- /.wrap-contactform-home1 -->
                </div><!-- /.col-md-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>

    <!-- Flat information box -->
    <section class="flat-row pad-top0px pad-bottom85px">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="flat-information-box inf1">
                        <span class="icon">
                            <i class="icon-Smartphone-4"></i>
                        </span>
                        <div class="content">
                            <div class="title">Telephone 1</div>                        
                            <p>+61 3 8376 6284</p> 
                        </div> 
                    </div><!-- /.flat-information-box -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3">
                    <div class="flat-information-box inf2">
                        <span class="icon">
                            <i class="icon-Smartphone-4"></i>
                        </span>
                        <div class="content">
                            <div class="title">Telephone 2</div>                        
                            <p>+61 3 8376 6284</p> 
                        </div> 
                    </div><!-- /.flat-information-box -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3">
                    <div class="flat-information-box inf3">
                        <span class="icon">
                            <i class="icon-Email"></i>
                        </span>
                        <div class="content">
                            <div class="title">Email</div>                        
                            <p>AlitStudios@gmail.com</p> 
                        </div> 
                    </div><!-- /.flat-information-box -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3">
                    <div class="flat-information-box inf4">
                        <span class="icon">
                            <i class="icon-Edit-Map"></i>
                        </span>
                        <div class="content">
                            <div class="title">Address</div>                        
                            <p>PO Box 16122 Collins Street</p> 
                        </div> 
                    </div><!-- /.flat-information-box -->
                </div><!-- /.col-md-3 -->
            </div>
        </div><!-- /.container -->
    </section>
    <%= render 'footer' %> 
</div>

app/views/home/courses.html.erb
<!-- Boxed -->
<div class="boxed">

    <%= render 'shelf' %>
    <%= render 'navigation' %>
    

<!-- Page title -->
    <div class="page-title parallax parallax1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">                    
                    <div class="page-title-heading">
                        <h1 class="title">Course Categories</h1>
                        <div class="breadcrumbs">
                            <ul>
                                <li><%= link_to 'Home',root_path %></li>
                                <li>Course Categories</li>
                            </ul>                   
                        </div>
                    </div><!-- /.page-title-captions --> 
                    
                </div><!-- /.col-md-12 -->  
            </div><!-- /.row -->  
        </div><!-- /.container -->                      
    </div><!-- /.page-title -->

    <!-- Fillter courses -->
    <section class="flat-row pad-top50px pad-bottom0px">
        <div class="container">
            <div class="row">
                <div class="search-course">
                    <div class="col-md-10">
                        <!-- Fillter courses -->
                        <form class="flat-contact-form fillter-courses border-radius border-white text-center style1" id="contactform5" method="post" action="./contact/contact-process.php">
                            <div class="field clearfix">      
                                <div class="wrap-type-input">
                                    <div class="wrap categories-courses">
                                        <select class="select-field categories-courses" name="appointment_services">
                                            <option value="" selected="selected">All courses </option>
                                            <option value="Categories 1">Courses 1</option>
                                            <option value="Categories 2">Courses 2</option>
                                            <option value="Categories 3">Courses 3</option>
                                        </select> 
                                    </div><!-- /.wrap-select -->
                                    
                                    <div class="wrap courses-keyword">
                                        <input type="text" value="" placeholder="Course keyword" name="subject" id="subject" >
                                    </div>

                                    <div class="wrap all-categories">
                                        <button>All categories</button>
                                    </div>  
                                </div><!-- /.wrap-type-input -->                            
                            </div><!-- /.field -->                        
                        </form><!-- /.comment-form -->  
                    </div><!-- /.col-md-10 -->

                </div><!-- /.search-course -->
            </div><!-- /.row -->
        </div><!-- /.container -->        
    </section>

    <!-- Flat courses -->
    <!-- Flat courses -->
    <section class="flat-row pad-bottom90px">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-section style1">
                        <h1 class="title">Popular Categories</h1>
                        <div class="desc">
                            <p>Vut sagittis a, magna ridiculus! Scelerisque parturient! Cum duis nunc in, dignissim, porta porta enim, proin<br> turpis egestas! Mauris dapibus sed integer placerat, scelerisque!</p>
                        </div>
                        <div class="icon">
                            <%= image_tag('icon/line.png') %>
                        </div>
                    </div><!-- /.title-section -->
                </div><!-- /.col-md-12 -->
            </div><!-- /.row -->

            <div class="row">
                <div class="flat-divider d55px"></div>
            </div>

            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat1.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Business and Economics</h6></a>
                            <p>Management, Marketing, Business</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat2.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Language</h6></a>
                            <p>English, French, Chinese</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Arts</h6></a>
                            <p>Design, Film, Photography</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Fashion</h6></a>
                            <p>Fashion Design, Fashion Marketing</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->
            </div><!-- /.row -->

            <div class="row">
                <div class="flat-divider d40px"></div>
            </div>

            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Health Studies</h6></a>
                            <p>Anesthesiology, Immunology</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Food and Beverage Studies</h6></a>
                            <p>Culinary Arts, Pastry</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Engineering & Technology</h6></a>
                            <p>IT, Computer Science, Engineering</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6 col-xs-6">
                    <div class="flat-courses">
                        <div class="courses-thumbnail">
                            <a href="#"><%= image_tag('cat3.jpg') %></a>
                             <%= link_to "View more",home_single_course_path,:class=>'courses-viewmore' %>
                        </div>
                        <div class="courses-content">
                            <a href="#"><h6 class="courses-topic">Humanities and Social Sciences</h6></a>
                            <p>Education, Media, Sociology</p>
                        </div>
                    </div><!-- /.flat-courses -->
                </div><!-- /.col-md-3 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.flat-row -->
   <%= render 'footer' %>
  </div>